apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  #type: ClusterIP
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080         # Service port
      targetPort: 8080   # Port the app listens on (matches containerPort)
  selector:
    app: api-gateway