spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://identity-service.default.svc.cluster.local:8081
          predicates:
            - Path=/auth/**

        - id: job_service
          uri: http://job-service.default.svc.cluster.local:8082
          predicates:
            - Path=/job/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.DispatcherHandler: TRACE
    reactor.netty.http.client: DEBUG

jwt:
  public-key: classpath:keys/public.pem